### ISSUE TITLE
Deploy application on GitHub pages

### ISSUE THREAD

**Issue by Kamba56** [Kamba56/Personla-Portfolio#7]
Deployed application on GitHub pages. The link is attached below.

https://kamba56.github.io/Personal-Portfolio/

**Comment by thecodechaser** [comment]
## STATUS: APPROVED 🟢

## Hi @Kamba56👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉
- Professional README file. :heavy_check_mark:
- Issue has a good title and summary. ✔️

<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
